"use client";
import { useState } from "react";
import { Upload, Loader2 } from "lucide-react";
import GlassPanel from "@/components/ui/GlassPanel";
import { COLORS } from "@/lib/constants";
const API = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";
type Result={label:string;confidence:number;probabilities:{label:string;probability:number}[]};
export default function FaultPredictionForm() {
  const [file,setFile]=useState<File|null>(null),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();if(!file)return setError("Choose a panel image first.");setLoading(true);setError("");const fd=new FormData();fd.append("image",file);try{const r=await fetch(`${API}/api/faults/predict`,{method:"POST",body:fd});const data=await r.json();if(!r.ok)throw Error(data.detail||"Prediction failed");setResult(data)}catch(e){setError(e instanceof Error?e.message:"Prediction failed")}finally{setLoading(false)}}
  const alternative=result ? result.probabilities.filter(p=>p.label!==result.label).sort((a,b)=>b.probability-a.probability)[0] : undefined;
  const advice:Record<string,string>={"Clean":"No fault is indicated. Continue normal monitoring and clean only according to the panel maintenance schedule.","Bird-drop":"Inspect and clean the affected area soon; localized bird droppings can create hot spots and reduce output.","Dusty":"Schedule cleaning. Compare production before and after cleaning to confirm recovery.","Electrical-damage":"Treat as high priority. Isolate the panel/string if required by site procedure and have a qualified technician inspect wiring, junction boxes, and hot spots.","Physical-Damage":"Arrange a physical inspection before continued operation; check for cracks, delamination, moisture ingress, or broken glass."};
  return <section id="fault-predictor" className="mt-5 scroll-mt-6"><GlassPanel accent={COLORS.amber} style={{padding:24}}><div className="glass-eyebrow" style={{color:COLORS.amber}}><Upload size={13}/> Try your own panel image</div><p className="mb-4 text-[12px]" style={{color:COLORS.muted}}>Upload a clear JPG, PNG, or WebP photo of one solar panel. The saved SolarGuard-Net checkpoint classifies it into the five trained fault classes.</p><form onSubmit={submit} className="flex flex-wrap items-center gap-3"><input aria-label="Solar panel image" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{setFile(e.target.files?.[0]||null);setResult(null)}} className="max-w-[260px] text-xs"/><button className="rounded-lg px-4 py-2 text-sm font-semibold text-black disabled:opacity-60" style={{background:COLORS.amber}} disabled={loading}>{loading?<Loader2 className="inline animate-spin" size={15}/>:"Predict fault"}</button>{file&&<span className="text-xs" style={{color:COLORS.muted}}>{file.name}</span>}</form>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}{result&&<><div className="mt-5 grid gap-3 md:grid-cols-[.7fr_1.3fr]"><div className="rounded-lg p-4" style={{background:"rgba(0,0,0,.22)"}}><div className="text-xs uppercase" style={{color:COLORS.muted}}>Prediction</div><div className="mt-1 text-xl font-semibold" style={{color:COLORS.text}}>{result.label}</div><div className="text-sm" style={{color:COLORS.amber}}>{result.confidence}% confidence</div></div><div className="space-y-1.5">{result.probabilities.map(p=><div key={p.label} className="flex gap-2 text-xs"><span className="w-32" style={{color:COLORS.muted}}>{p.label}</span><div className="h-2 flex-1 rounded" style={{background:"rgba(255,255,255,.08)"}}><div className="h-2 rounded" style={{width:`${p.probability}%`,background:COLORS.amber}}/></div><span className="w-10 text-right" style={{color:COLORS.text}}>{p.probability}%</span></div>)}</div></div><div className="mt-4 rounded-lg border p-4 text-sm" style={{borderColor:`${COLORS.cyan}55`,background:"rgba(6,182,212,.06)"}}><div className="font-semibold" style={{color:COLORS.cyan}}>Why this result?</div><p className="mt-1.5 text-xs leading-5" style={{color:COLORS.muted}}><b style={{color:COLORS.text}}>{result.confidence}% confidence</b> means this class received the largest share of the model&apos;s probability across its five trained categories. {alternative&&<>The closest alternative is <b style={{color:COLORS.text}}>{alternative.label}</b> at {alternative.probability}%.</>} A lower confidence or a close alternative means the image is visually ambiguous; take another well-lit, close-up photo and confirm important faults with a technician.</p><p className="mt-2 text-xs leading-5" style={{color:COLORS.muted}}><b style={{color:COLORS.text}}>Recommended next step:</b> {advice[result.label]}</p></div></>}</GlassPanel></section>
}